#!/usr/bin/env python3

PYTHON = '.py'
MARKDOWN = '.md'
JAVASCRIPT = '.js'
JAVA = '.java'
HTML = '.html'
TEXT = '.txt'

fileExtMapping = {
        'py': PYTHON, '.py': PYTHON,
        'python': PYTHON, '.python': PYTHON,
        'md': MARKDOWN, '.md': MARKDOWN,
        'markdown': MARKDOWN, '.markdown': MARKDOWN,
        'js': JAVASCRIPT, '.js': JAVASCRIPT,
        'javascript': JAVASCRIPT, '.javascript': JAVASCRIPT,
        'java': JAVA, '.java': JAVA,
        'html': HTML, '.html': HTML,
        'txt': TEXT, '.txt': TEXT, 'text': TEXT, '.text': TEXT
        }


def simpleNote(name, ext='md'):
    notesDir = os.path.expanduser('~/Desktop/Notes')
    ext = fileWithExtension(ext)
    if ext is None:
        print('[-] Invalid file extension')
        return
    name = name + ext
    filePath, searchedNotes = findFile(name, notesDir)
    if filePath:
        print('[+] The notes already exist, opening ' + name)
        print(filePath)
        os.system('vim ' + filePath)
    else:
        os.chdir(notesDir + '/General_Notes')
        fileNew = open(name, 'w')
        fileNew.close()
        print('[+] New notes file: ' + name + ' created')
        os.system('vim ' + name)


def findFile(name, startDir):
    foundPaths = {startDir: {}}
    found = False
    try:
        toEval = os.listdir(startDir)
    except:
        if name in startDir:
            found = startDir
            return found, startDir
        else:
            return False, None

    while len(toEval) > 0 and not found:
        newDir = startDir + '/' + toEval[0]
        print(newDir)
        toEval.pop(0)
        found, foundPaths[startDir][newDir] = findFile(name, newDir)
    if found:
        print('[+] ' + name + ' exists, returning path to file')
        foundPaths = newDir
        return found, newDir
    return found, foundPaths


def fileWithExtension(ext):
    ext = ext.lower()
    if ext not in fileExtMapping.keys():
        print('[-] invalid file type')
        return
    else:
        return fileExtMapping[ext]


def folderNotes(name, folder, ext):
    notesDir = os.path.expanduser('~/Desktop/Notes')
    findFolder(folder, notesDir)


def findFolder(folderName, startDir):
    folders = os.listdir(startDir)
    folderPath = False
    for folder in folders:
        if folder == folderName:
            folderPath = startDir + '/' + folder
            break
        else:
            pass
    if not folderPath:
        folderPath = startDir + '/' + folderName
        os.makedirs(folderPath)
    os.chdir(folderPath)
    print(os.getcwd())



def main():
    if len(sys.argv) == 1:
        print("[-] No inputs supplied, for help see -h for documentation")
        return
    inputs = sys.argv[1:]
    if inputs[0] not in ['nfe', 'ne', 'n']:
        print('[-] Please use a valid input, for help see the documentation')
        return
    if inputs[0] == 'nfe':
        folderNotes(inputs[1], inputs[2], inputs[3])
        return
    elif inputs[0] == 'ne':
        simpleNote(inputs[1], inputs[2])
        return
    elif inputs[0] == 'n':
        simpleNote(inputs[1])
        return
    else:
        print('[-] Please enter a valid input, for help see the documentation')
        return


if __name__ == "__main__":
    import sys
    import os
    main()
